{% set name = "rjsmin" %}
{% set version = "1.2.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rjsmin-{{ version }}.tar.gz
  sha256: 1f982be8e011438777a94307279b40134a3935fc0f079312ee299725b8af5411

build:
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - pip
  run:
    - python

test:
  imports:
    - rjsmin
    - _rjsmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ndparker/rjsmin
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: Fast javascript minifier for Python
  description: |
    rJSmin is a javascript minifier written in python. The minifier is based on the semantics of jsmin.c by Douglas Crockford.
    The module is a re-implementation aiming for speed, so it can be used at runtime (rather than during a preprocessing step).
  doc_url: http://opensource.perlig.de/rjsmin/doc-1.0/index.html
  dev_url: https://github.com/ndparker/rjsmin

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
