{% set name = "rjsmin" %}
{% set version = "1.2.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/rjsmin-{{ version }}.tar.gz
  sha256: 1388b52493a4c04fbc970a2d757c301fa05a3c37640314c2ce9dfc8d8a730cc6

build:
  noarch: generic
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
  host:
    - python >=3.8
    - pip
    - setuptools
  run:
    - python >=3.8

test:
  imports:
    - rjsmin
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/ndparker/rjsmin
  summary: Javascript Minifier
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE

extra:
  recipe-maintainers:
    - cshaley
    - sannykr
    - rxm7706
